### ISSUE TITLE
Hello, there's seems to be issues with world gen.

### ISSUE THREAD

**Issue by asteroidb12** [LudoCrypt/The-Corners#1]
I am currently using Fabric 1.17.1

I started a world in minecraft, then placing and entering the painting leads me to an empty void that is a long fall. It happened twice when creating two new worlds.

latest log: [latest.log](https://github.com/LudoCrypt/The-Corners/files/7140585/latest.log)

screenshot:
![2021-09-09_17 40 56](https://user-images.githubusercontent.com/68461874/132783177-a63d06b6-0e5c-493e-b181-6371159eef6c.png)

**Comment by LudoCrypt** [comment]
This is not a bug, the generation just takes a while to load as it is 2000 or so blocks tall. I should add a config option for this though. As for the sky being black, i have genuinely no idea why that happens.
