### ISSUE TITLE
The game crashed whilst ticking player

### ISSUE THREAD

**Issue by ThePhoneGuy1** [LudoCrypt/The-Corners#11]
When I enter either of The Corners 1.1.4 dimensions in a world that was made before installing the mod
and it gives me this
The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_27983()" because "world" is null
Exit Code: -1
and this crash log
[crash-2022-01-27_19.09.27-server.txt](https://github.com/LudoCrypt/The-Corners/files/7955029/crash-2022-01-27_19.09.27-server.txt)

**Comment by X-XLebyshek** [comment]
Hey, I'm having the same isssue on Quilt 1.19.2, I'm sorry if I don't really understand what [f405e9f](https://github.com/LudoCrypt/The-Corners/commit/f405e9f4542ff19e9795e55d9c74bea0cc83b050) means, but I think it says upgrading to version 1.1.5 right? Well I have version 1.2.4, and it still crashes. To be fair though, it crashes only once, and then I can use the world normally after.
