### ISSUE TITLE
Bad type on operand stack

### ISSUE THREAD

**Issue by NovoTheOG** [LudoCrypt/The-Corners#13]
Whenever i tried to launch the game with the current fabric api i would get an error message saying "Error: java.lang.VerifyError: Bad type on operand stack" and "Exit code -1" is there any way to fix this?

**Comment by LudoCrypt** [comment]
could you provide your latest.log and or debug.log

**Comment by NovoTheOG** [comment]
[crash-2022-02-21_23.31.20-client.txt](https://github.com/LudoCrypt/The-Corners/files/8116550/crash-2022-02-21_23.31.20-client.txt)
theres the whole crash report idk if thats an option but idk really how to pull those without the game

**Comment by LudoCrypt** [comment]
this isnt an issue with the corners.
