### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by H46K3RL0L** [LudoCrypt/The-Corners#14]
whenever I try to play or create a world it crashes, I've tried all the fixes in the crash report, helped but didn't work. here's the crash reports:
[hs_err_pid6548.log](https://github.com/LudoCrypt/The-Corners/files/8405167/hs_err_pid6548.log)
[hs_err_pid21828.log](https://github.com/LudoCrypt/The-Corners/files/8405168/hs_err_pid21828.log)
[hs_err_pid22856.log](https://github.com/LudoCrypt/The-Corners/files/8405169/hs_err_pid22856.log)

**Comment by H46K3RL0L** [comment]
[hs_err_pid19576.log](https://github.com/LudoCrypt/The-Corners/files/8405189/hs_err_pid19576.log)

**Comment by LudoCrypt** [comment]
No clue, probably fixed
