### ISSUE TITLE
Breaks Fabric rendering API on Quilt?

### ISSUE THREAD

**Issue by goldenapple3** [LudoCrypt/The-Corners#16]
I noticed that items from many different mods do not render in my pack, I think I narrowed it down to The Corners.

Did some tests with Industrial Revolution as well as Sodium/Indium/Iris.
* IndRev + The Corners = some machine blocks and items do not render
* IndRev + The Corners + Sodium/Indium/Iris = blocks render but items don't
* IndRev by itself, or with Sodium/Indium/Iris = works
```
cloth-config-6.2.57-fabric.jar
fabric-language-kotlin-1.7.2+kotlin.1.6.20.jar
indrev-1.14.0-BETA.jar
qsl-1.1.0-beta.8_qfapi-1.0.0-beta.14_fapi-0.51.1_mc-1.18.2.jar
satin-1.7.2.jar
indium-1.0.3+mc1.18.2.jar
iris-mc1.18.2-1.2.4-build.38.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
the-corners-1.2.1.jar
```
I think that has to do with the Fabric Rendering API? I don't really know.

**Comment by LudoCrypt** [comment]
Fixed in 1.2.7
