### ISSUE TITLE
Invisible Items with Tech Reborn/Industrial Revolution & Create

### ISSUE THREAD

**Issue by Gamerbolts** [LudoCrypt/The-Corners#17]
Hello. I was having issues with missing items textures for the above 3 mods and could not figure out why. After a lot of testing I have found that it is The Corners mod causing this. I am not sure why this is but here is the log.
[latest.log](https://github.com/LudoCrypt/The-Corners/files/8844189/latest.log)

This is a small portion of my modpack. I am not sure if this log will help but I wanted to just get it out there that there is a conflict between your mod and the other three.

**Comment by goldenapple3** [comment]
Caused by #16

**Comment by LudoCrypt** [comment]
Fixed in 1.2.7
