### ISSUE TITLE
Communal Corridors Glitchy

### ISSUE THREAD

**Issue by cymophic** [LudoCrypt/The-Corners#22]
![image](https://user-images.githubusercontent.com/97153344/183239654-fcd7fdc7-5cec-4f3e-aca3-1debf2004059.png)
![image](https://user-images.githubusercontent.com/97153344/183239656-678246ff-dacc-409e-b29f-f965570d33b4.png)

**Comment by LudoCrypt** [comment]
Works as intended. You can turn this off in config
