### ISSUE TITLE
major incompatibility with ad astra

### ISSUE THREAD

**Issue by DeRp-MaSte5** [LudoCrypt/The-Corners#25]
If you even look at a water pump with Corners in the modpack, not even in the dimension, you crash. I have already gone to Ad Astra for this and they just say it's caused by this mod when reading the crash report. The crash is really annoying due to roughly enough items also crashing it if you look at a water pump.
[crash-2022-08-19_22.39.27-client.txt](https://github.com/LudoCrypt/The-Corners/files/9387500/crash-2022-08-19_22.39.27-client.txt)

**Comment by LudoCrypt** [comment]
This is fixed in the 1.19 version
