### ISSUE TITLE
Blocks not Rendering in the Dimension Only.

### ISSUE THREAD

**Issue by SSightss** [LudoCrypt/The-Corners#26]
For some reason no blocks are rendering in the dimensions, only the one with the railings, I would assume I am looking at the skybox surrounding me. Is there a fix for this? I disabled the strong shaders in config and it did not work.
![2022-08-25_23 44 05](https://user-images.githubusercontent.com/41082417/186831743-be8a8fb3-1364-4fad-bb13-48e6a4fa7cd7.png)
The image above is what I'm seeing when I enter the dimension, the block indicator at the top shows the block being there but not rendered.
I will add I can leave the dimension the same way with placing and lighting a painting with the flint and steel just doing it blind lol.

**Comment by LudoCrypt** [comment]
What are all the mods you are using?

**Comment by SSightss** [comment]
[FABRIC SERVER.zip](https://github.com/LudoCrypt/The-Corners/files/9435482/FABRIC.SERVER.zip)
The list of mods are in "modlist.html" we are using version 1.18.2.

**Comment by JelloJeffrey** [comment]
I experienced the exact same issue on 1.18. I did some VERY rudimentary testing (I just tried turning off and on some mods to see what worked) and I found that the create mod seems to be the cause. I honestly have no clue why (not really good with coding things :P), but assuming this thread is still relevant I just thought I would put in my findings. Hope it can get fixed!
