### ISSUE TITLE
Pre-Existing worlds crash when entering paintings

### ISSUE THREAD

**Issue by GayHyena** [LudoCrypt/The-Corners#3]
Hi there. So, I downloaded this mod a couple of days ago and yesterday I tried going into this new dimension the mod adds, but when I did, it crashed my game. And now I can't even open my minecraft world without it crashing my game immediately upon entry to my world. I would really appreciate you fixing this problem ASAP.

**Comment by LudoCrypt** [comment]
Can you provide a crash report or your latest.log?

**Comment by GayHyena** [comment]
Yes I can.

[crash-2021-09-13_15.43.54-server.txt](https://github.com/LudoCrypt/The-Corners/files/7156984/crash-2021-09-13_15.43.54-server.txt)

**Comment by LudoCrypt** [comment]
Hmm, what happens when you try again on a new world?

**Comment by GayHyena** [comment]
Well I haven't tried to make a new world yet but my current issue is that when I try to enter my current world, it spawns me right in front of the painting and my game crashes. I've tried disabling the mod to see if that would fix the problem and it didn't.

**Comment by LudoCrypt** [comment]
Im aware, but the issue could be apart of fapi's registry. So if you make a new world and it works, then your world normally would be the issue. I want you to make a new world and see if it still breaks when you go into a portal. If it does then can you please provide your latest.log as well?

**Comment by GayHyena** [comment]
Sure, were do I find the latest.log?

**Comment by LudoCrypt** [comment]
.minecraft/logs/latest.log

**Comment by GayHyena** [comment]
So I made a new super flat world in creative and entered one of the paintings and it worked, so what now? Do I have to start a new survival world?

**Comment by LudoCrypt** [comment]
Hm, was the crashing world a world before you installed the mod, or what is created after you put in the mod?

**Comment by GayHyena** [comment]
Before I installed the mod.

**Comment by LudoCrypt** [comment]
Okay, this is probably an issue with how im registering the dimensions then. Ill look into this

**Comment by GayHyena** [comment]
Alrighty then, thank you.

**Comment by LudoCrypt** [comment]
Just undid the mixin that 'fixed' this, the mixin also didnt fix this.
