### ISSUE TITLE
v1.2.2 (released for 1.18.2) requires a mod only released for 1.19

### ISSUE THREAD

**Issue by green8751** [LudoCrypt/The-Corners#30]
in the launcher log i get this:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Satin' (satin) 1.11.0 with any version that is compatible with:
		 - fabric-rendering-v1 1.10.8+54e5b2ec60
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Satin' (satin) 1.11.0 requires version 2.1.0 or later of mod 'Fabric Rendering (v1)' (fabric-rendering-v1), but only the wrong version is present: 1.10.8+54e5b2ec60!
	 - Mod 'Satin' (satin) 1.11.0 requires version 1.19.3 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!

im not sure if this is a result of you just checking all the boxes when uploading, or if you uploaded the wrong version, but it wont launch without satin eather

**Comment by LudoCrypt** [comment]
https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3595997
