### ISSUE TITLE
Crashes on server (shouldn't Special Models be a client mod?)

### ISSUE THREAD

**Issue by acikek** [LudoCrypt/The-Corners#33]
Was trying to run a server with the latest version of The Corners on 1.20.1, and here's the [latest.log](https://github.com/LudoCrypt/Special-Models/files/11910318/latest.log) with the crash.

I had a look through Special Models and I'm certain you intended for it to be a client mod since you directly reference client classes. In The Corners, you also initialize the special models in the common initializer instead of a client initializer, so this is ultimately also an issue with this mod.

**Comment by LudoCrypt** [comment]
whoopsie

**Comment by LudoCrypt** [comment]
oh also special models needs to be a non-client-only mod because the way it works requires a registry of some kind. What I missed was just making sure everything on the client side of things was only loaded if its on the client

**Comment by LudoCrypt** [comment]
Fixed in 1.2.7
