### ISSUE TITLE
Crash with Ecotones

### ISSUE THREAD

**Issue by ChloeDawn** [LudoCrypt/The-Corners#34]
When launched alongside Ecotones, the game crashes as Limlib attempts to register something twice.
This does not occur when I disable Ecotones in this minimal testing environment.

**Ecotones:** https://modrinth.com/mod/ecotones

**Minecraft version:** 1.20.1
**Mod version:** 1.2.6
**Ecotones version:** 0.9.3
**Quilt Loader version:** 0.19.2
**Quilted Fabric API version:** 7.0.6+0.85.0+1.20.1

**Crash report:** https://mclo.gs/91ktPIq

**Comment by LudoCrypt** [comment]
Fixed in 1.2.7, at least my end of it. ecotones crashes anyways for a different bug
