### ISSUE TITLE
Extreme FPS lag in communal corridors 

### ISSUE THREAD

**Issue by DooveyTheDoove** [LudoCrypt/The-Corners#36]
Mod version: 1.2.3 (mc version 1.19.2)
Issue: Extreme fps lag in the communal corridors
Other installed mods: Many, but I'm fairly certain they're not the ones causing this, I'm saying that because the other corner dimensions/levels dont lag at all, it's only the corridor one lol.
Log thing idk: https://mclo.gs/xThqhkY
Additional info: At first, I thought it was because of the distorted shader, disabling that did nothing. Also staring right at the floor will clear the lag completely for some strange reason.
![wow so laggy](https://github.com/LudoCrypt/The-Corners/assets/132660288/516bc360-6cd6-4756-90f0-a5b9a36f2005)
![mmm floor](https://github.com/LudoCrypt/The-Corners/assets/132660288/533facee-3be6-498d-8cba-1bd3131f1fc1)

**Comment by LudoCrypt** [comment]
fixed in later versions
