### ISSUE TITLE
Canvas Renderer

### ISSUE THREAD

**Issue by Deathron99** [LudoCrypt/The-Corners#5]
I believe that I have found an issue with this mod and Canvas Renderer, I suspect the the addition of The Communal Corridors to be the breaking difference between this current version and the previous versions. The "suspected" mods stated in the crash report do not cause issues when ran without the addition of Canvas Renderer.

 

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
Exit Code: -1

 

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/17/21, 6:55 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
at net.minecraft.client.font.EmptyGlyphRenderer.<init>(EmptyGlyphRenderer:10)
at net.minecraft.client.font.FontStorage.<clinit>(FontStorage:27)
at net.minecraft.client.font.FontManager.<init>(FontManager:48)
at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:527)
at net.minecraft.client.main.Main.main(Main:179)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at net.minecraft.class_384.<init>(class_384.java:10)
at net.minecraft.class_377.<clinit>(class_377.java:27)
at net.minecraft.class_378.<init>(class_378.java:48)
at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
Minecraft Version: 1.17.1
Minecraft Version ID: 1.17.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 16.0.1, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 2098896896 bytes (2001 MiB) / 3120562176 bytes (2976 MiB) up to 4294967296 bytes (4096 MiB)
CPUs: 12
Processor Vendor: GenuineIntel
Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
Identifier: Intel64 Family 6 Model 165 Stepping 3
Microarchitecture: unknown
Frequency (GHz): 2.90
Number of physical packages: 1
Number of physical CPUs: 6
Number of logical CPUs: 12
Graphics card #0 name: Intel(R) UHD Graphics 630
Graphics card #0 vendor: Intel Corporation (0x8086)
Graphics card #0 VRAM (MB): 1024.00
Graphics card #0 deviceId: 0x9bc8
Graphics card #0 versionInfo: DriverVersion=27.20.100.9415
Graphics card #1 name: NVIDIA GeForce GTX 1660
Graphics card #1 vendor: NVIDIA (0x10de)
Graphics card #1 VRAM (MB): 4095.00
Graphics card #1 deviceId: 0x2184
Graphics card #1 versionInfo: DriverVersion=27.21.14.6079
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 3.20
Memory slot #0 type: DDR4
Memory slot #1 capacity (MB): 8192.00
Memory slot #1 clockSpeed (GHz): 3.20
Memory slot #1 type: DDR4
Virtual memory max (MB): 25436.72
Virtual memory used (MB): 15618.47
Swap memory total (MB): 9216.00
Swap memory used (MB): 416.63
JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
Fabric Mods:
adventurez: AdventureZ 1.3.0
apoli: Apoli 2.0.3
artifice: Artifice 0.15.3+21w07a
autoconfig1u: Auto Config v1 Updated 3.3.1
automatone: Automatone 0.4.1
bclib: BCLib 0.3.1
betterend: Better End 0.11.0-pre
betterf3: BetterF3 1.1.5
betternether: Better Nether 5.1.3
black-powder: Black Powder 1.0.6
blast: BLAST 1.8
blockus: Blockus 2.2.10+1.17.1
calio: Calio 1.0.3
campanion: Campanion 2.0.0-beta.1
canvas: Canvas Renderer 1.0.2035
cardinal-components: Cardinal Components API 3.1.1
cardinal-components-base: Cardinal Components API (base) 3.1.1
cardinal-components-block: Cardinal Components API (blocks) 3.1.1
cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
cardinal-components-entity: Cardinal Components API (entities) 3.1.1
cardinal-components-item: Cardinal Components API (items) 3.1.1
cardinal-components-level: Cardinal Components API (world saves) 3.1.1
cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
cardinal-components-util: Cardinal Components API (utilities) 3.1.1
cardinal-components-world: Cardinal Components API (worlds) 3.1.1
carvepump: Carve My Pumpkin 1.0.4
chime: Chime 1.2.0-SNAPSHOT
chipped: Chipped 1.1.1
cloth-basic-math: Cloth Basic Math 0.5.1
cloth-config2: Cloth Config v5 5.0.38
com_flowpowered_flow-math: flow-math 1.0.3
com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
compactstatuseffects: Compact Status Effects 2.0.1
companion_bats: Companion Bats 1.17.9
connected-doors: Connected Doors 1.1+1.17
corners: The Corners 1.1.0
cosmetica: Cosmetica 0.2.0
crawl: Crawl 0.9.3
creeperspores: Creeper Spores 1.6.0
dark-loading-screen: Dark Loading Screen 1.6.11
darkness: True Darkness 1.6.74
de_javagl_obj: obj 0.3.0
dimdoors: DimensionalDoors 4.0.0+beta.3-10.10.2021
disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
dual_riders: DualRiders 1.0.5
eggtab: Egg Tab 2.1.0+1.16-fabric
enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
endrem: End Remastered 4.1.0
enhancedcelestials: Enhanced Celestials 2.0.5
expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
extraalchemy: Extra Alchemy 1.6.1
extraorigins: Extra Origins 1.17-9
fabric: Fabric API 0.41.0+1.17
fabric-api-base: Fabric API Base 0.3.0+a02b446313
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
fabricenchantments: Fabric Enchantments 0.4.2
fabricloader: Fabric Loader 0.11.7
fabricshieldlib: Fabric Shield Lib 1.4.0
fallflyinglib: FallFlyingLib 3.0.0-beta.2
fallingleaves: Falling Leaves 1.7.4+1.17.1
farsighted-mobs: Farsighted Mobs 1.0a-1.17
fastfurnace: FastFurnace 1.17-3.0
fasttransferlib: Fast Transfer Lib 0.5.6
fermion: Fermion 2.11.244
fermion-modkeys: Fermion Modifier Keys 1.10.241
fermion-orientation: Fermion Orientation 1.2.244
fermion-varia: Fermion Varia 2.6.244
fiber: fiber 0.23.0-2
fiber2cloth: Fiber To Cloth 3.1.1
figura: Figura 0.0.6
frex: FREX 5.6.255
geckolib3: Geckolib 3.0.16
ghastly_wail: Ghastly Wail 1.0.3+MC1.17-1.17.1
graveyard: The Graveyard 1.0
grondag_bitraster: bitraster 1.5.47
heartbond: Heartbond 1.1.0
hellish-materials: Hellish Materials 0.13.1
herdspanic: Herds Panic 1.0.3
illuminations: Illuminations 1.9
impaled: Impaled 1.0.1
impersonate: Impersonate 2.3.5
jankson: Jankson 3.0.1+j1.2.0
java: OpenJDK 64-Bit Server VM 16
json-model-extensions: JSON Model Extensions 1.22.203
kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
kirin: Kirin UI 1.9.1
lacrimis: Lacrimis 2.1.3+1.17.1
lambdynlights: LambDynamicLights 2.0.2+1.17
libblockattributes: LibBlockAttributes 0.8.17003
libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
libcd: LibCapableData 3.0.3+1.16.3
libgui: LibGui 4.1.4+1.17.1
libninepatch: LibNinePatch 1.1.0
light-fix: light-fix 1.0.0
locki: Locki 0.5.0
lovely_snails: Lovely Snails 1.0.3+1.17
matrix: Matrix 1.0.0
maybe-data: Maybe data 1.0.1-1.17
mermod: Mermod 1.9
midnightlib: MidnightLib 0.2.6
minecraft: Minecraft 1.17.1
mm: Manningham Mills 2.3
modify-drops-api: Modify Drops API 0.3.2
morerespawnanchors: More Respawn Anchors 1.0.2
morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
morevillagesmod: More Villages Mod 1.0.0
multi_item_lib: Multi Item Lib 1.4.0
mypack: My Pack 1.0.0
mythic-mounts: Mythic Mounts 1.17.1-2.0
nomoreglowingpots: No More Glowing Pots 1.0.2
noplayerlabels: No Player Labels 2.0.2
notenoughcrashes: Not Enough Crashes 3.7.0+1.17.1
npcvariety: NPC Variety 2.1.3
nyfsquivers: Nyf's Quivers Fabric-0.2.6
omega-config: OmegaConfig 1.0.8
onsoulfire: On Soul Fire 1.17-3
org_anarres_jcpp: jcpp 1.4.14
org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
org_luaj_luaj-jse: luaj-jse 3.0.1
org_objenesis_objenesis: objenesis 3.2
origins: Origins 1.1.2
origins-classes: Origins: Classes 1.2.2
particlerain: Particle Rain 1.5.0
patchouli: Patchouli 1.17.1-56-FABRIC
pehkui: Pehkui 2.4.0+1.14.4-1.17.1
plantinajar: Plant In A Jar 2.2.2
playerabilitylib: Pal 1.3.0
presencefootsteps: Presence Footsteps r32-1.17-rc1
rare-ice: Rare Ice 0.3.0
ratsmischief: Rat's Mischief 1.2.3
reach-entity-attributes: Reach Entity Attributes 2.1.1
realisticfirespread: Realistic Fire Spread 1.17-3
requiem: Requiem 2.0.0-alpha.12
requiem-core: Requiem-Core 2.0.0-alpha.12
requiemapi: Requiem-API 2.0.0-alpha.12
rocks: This Rocks! 1.5.1
satin: Satin 1.6.4
scorch: Scorch 1.1.2
secretrooms: Secret Rooms 1.1.0+1.17
sit: Sit 1.17.1-13
skinlayers: 3d Skin Layers 1.1.1
smart-recipes: Smart Recipes 0.1.0+1.17
somnus: Somnus API 0.0.14-1.17.1
special-circumstances: Special Circumstances 1.9.244
spruceui: SpruceUI 3.2.0+1.17
static-content: Static Content 1.0.1-1.16.2
staticdata: Static Data 1.1.2
stoneholm: Stoneholm 1.3
stonevaults: Stonevaults 1.1.0
stuffz: StuffZ 2.3.2
sync: Sync (Fabric) 1.2
team_reborn_energy: Energy 0.1.1
terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
totemmod: Wither Totems Mod 0.3.2
trade: Trade 1.2.1
transliterationlib: TRansliterationLib 1.2.2
trinkets: Trinkets 3.0.4
trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
villagerfix: Villager Trade Fix 1.0.0
visuality: Visuality 0.2.0
visualoverhaul: VisualOverhaul 3.3.0
voicechat: Simple Voice Chat 1.17.1-1.1.9
voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
voidz: VoidZ 1.0.5
wildfire_gender: Wildfire's Female Gender Mod 2.8
william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.7
wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
wrenchable: Wrenchable 1.1.0+1.17
xps: Xp Obelisk 0.2.0_for_1.17.x_Fabric
Launched Version: fabric-loader-0.11.7-1.17.1
Backend library: LWJGL version 3.2.2 build 10
Backend API: GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.79, NVIDIA Corporation
Window size: <not initialized>
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
Suspected Mods: Fabric Loader (fabricloader), Extra Alchemy (extraalchemy)

**Comment by LudoCrypt** [comment]
Canvas shmanshmas, i got it to work with Iris, so look out for that in the next update ^^
Unfortunately, i do not care to make Canvas support, so i will be closing this issue as inoperable.
