### ISSUE TITLE
Crash with Roughly Enough Items, Modern Industrialization, and The Corners

### ISSUE THREAD

**Issue by WolfBV** [LudoCrypt/The-Corners#7]
Load up an instance with those 3 mods, use RER's U key to look up what any item can be used for, crash.

Modern Industrialization 0.7.0-alpha.01 and 0.6.1
ReI 6.2.335
The Corners 1.1.1

https://pastebin.com/SLH5nCLH

**Comment by LudoCrypt** [comment]
Unable to reproduce, but theoretically fixable?

**Comment by WolfBV** [comment]
ig it's just my computer then

**Comment by LudoCrypt** [comment]
try the latest version 1.1.2

**Comment by WolfBV** [comment]
Fixed with version 0.7.0 of Modern Industrialization.
