### ISSUE TITLE
Loading Loop

### ISSUE THREAD

**Issue by NovaTheArtist** [LudoCrypt/The-Corners#9]
So i'm not sure if this is a fabric problem or a corners problem but when trying to launch the game it enters an infinite loop of loading and then showing the title screen for a split second before loading again and repeating. Im not super familiar with fabric so.

**Comment by NovaTheArtist** [comment]
Sorry about that, got confused

**Comment by LudoCrypt** [comment]
Can you provide your latest.log? its located in .minecraft/logs/latest.log

**Comment by NixityNull** [comment]
I've been having the same problem, as well as the text turning into rectangles.

The latest.log file just says it has errors rendering textures over and over.

**Comment by oli314159** [comment]
Im suddenly having the same issue, i didn't change anything tho.. is there a solution for this?

**Comment by LudoCrypt** [comment]
Please provide your latest.log file, upload the full thing to pastebin or a different text sharing site. I have to see the full log

**Comment by LaughRat28** [comment]
> Please provide your latest.log file, upload the full thing to pastebin or a different text sharing site. I have to see the full log

i have the same problem (both 1.17.1 and 1.19.1) and here is my log for the 1.19.1 
[latest.log](https://github.com/LudoCrypt/The-Corners/files/11626172/latest.log)

**Comment by LudoCrypt** [comment]
What's your operating system?

**Comment by LaughRat28** [comment]
> 

Mine is windows 10, also the version of the mod i've tried is 1.2.3 and 1.1.2. I thought that was bc of the other mods but when i try this mod alone it still crash

**Comment by LudoCrypt** [comment]
Closing until people report it on 1.2.7
